apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexu.web.fullname" . }}
  namespace: {{ include "nexu.namespace" . }}
  labels:
    {{- include "nexu.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nexu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
