// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetV1BotsData, GetV1BotsResponse, PostV1BotsData, PostV1BotsResponse, PostV1BotsError, DeleteV1BotsByBotIdData, DeleteV1BotsByBotIdResponse, DeleteV1BotsByBotIdError, GetV1BotsByBotIdData, GetV1BotsByBotIdResponse, GetV1BotsByBotIdError, PatchV1BotsByBotIdData, PatchV1BotsByBotIdResponse, PatchV1BotsByBotIdError, PostV1BotsByBotIdPauseData, PostV1BotsByBotIdPauseResponse, PostV1BotsByBotIdPauseError, PostV1BotsByBotIdResumeData, PostV1BotsByBotIdResumeResponse, PostV1BotsByBotIdResumeError, GetV1BotsByBotIdChannelsSlackOauthUrlData, GetV1BotsByBotIdChannelsSlackOauthUrlResponse, GetV1BotsByBotIdChannelsSlackOauthUrlError, PostV1BotsByBotIdChannelsSlackConnectData, PostV1BotsByBotIdChannelsSlackConnectResponse, PostV1BotsByBotIdChannelsSlackConnectError, GetV1BotsByBotIdChannelsData, GetV1BotsByBotIdChannelsResponse, GetV1BotsByBotIdChannelsError, DeleteV1BotsByBotIdChannelsByChannelIdData, DeleteV1BotsByBotIdChannelsByChannelIdResponse, DeleteV1BotsByBotIdChannelsByChannelIdError, GetV1BotsByBotIdChannelsByChannelIdStatusData, GetV1BotsByBotIdChannelsByChannelIdStatusResponse, GetV1BotsByBotIdChannelsByChannelIdStatusError, PostV1InviteValidateData, PostV1InviteValidateResponse, GetV1ModelsData, GetV1ModelsResponse, GetApiInternalPoolsByPoolIdConfigData, GetApiInternalPoolsByPoolIdConfigResponse, GetApiInternalPoolsByPoolIdConfigError, PostApiInternalPoolsRegisterData, PostApiInternalPoolsRegisterResponse, PostApiInternalPoolsHeartbeatData, PostApiInternalPoolsHeartbeatResponse, GetApiInternalPoolsByPoolIdConfigLatestData, GetApiInternalPoolsByPoolIdConfigLatestResponse, GetApiInternalPoolsByPoolIdConfigLatestError, GetApiInternalPoolsByPoolIdConfigVersionsByVersionData, GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponse, GetApiInternalPoolsByPoolIdConfigVersionsByVersionError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getV1Bots = <ThrowOnError extends boolean = false>(options?: Options<GetV1BotsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetV1BotsResponse, unknown, ThrowOnError>({
        url: '/v1/bots',
        ...options
    });
};

export const postV1Bots = <ThrowOnError extends boolean = false>(options?: Options<PostV1BotsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostV1BotsResponse, PostV1BotsError, ThrowOnError>({
        url: '/v1/bots',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteV1BotsByBotId = <ThrowOnError extends boolean = false>(options: Options<DeleteV1BotsByBotIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteV1BotsByBotIdResponse, DeleteV1BotsByBotIdError, ThrowOnError>({
        url: '/v1/bots/{botId}',
        ...options
    });
};

export const getV1BotsByBotId = <ThrowOnError extends boolean = false>(options: Options<GetV1BotsByBotIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetV1BotsByBotIdResponse, GetV1BotsByBotIdError, ThrowOnError>({
        url: '/v1/bots/{botId}',
        ...options
    });
};

export const patchV1BotsByBotId = <ThrowOnError extends boolean = false>(options: Options<PatchV1BotsByBotIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<PatchV1BotsByBotIdResponse, PatchV1BotsByBotIdError, ThrowOnError>({
        url: '/v1/bots/{botId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const postV1BotsByBotIdPause = <ThrowOnError extends boolean = false>(options: Options<PostV1BotsByBotIdPauseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostV1BotsByBotIdPauseResponse, PostV1BotsByBotIdPauseError, ThrowOnError>({
        url: '/v1/bots/{botId}/pause',
        ...options
    });
};

export const postV1BotsByBotIdResume = <ThrowOnError extends boolean = false>(options: Options<PostV1BotsByBotIdResumeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostV1BotsByBotIdResumeResponse, PostV1BotsByBotIdResumeError, ThrowOnError>({
        url: '/v1/bots/{botId}/resume',
        ...options
    });
};

export const getV1BotsByBotIdChannelsSlackOauthUrl = <ThrowOnError extends boolean = false>(options: Options<GetV1BotsByBotIdChannelsSlackOauthUrlData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetV1BotsByBotIdChannelsSlackOauthUrlResponse, GetV1BotsByBotIdChannelsSlackOauthUrlError, ThrowOnError>({
        url: '/v1/bots/{botId}/channels/slack/oauth-url',
        ...options
    });
};

export const postV1BotsByBotIdChannelsSlackConnect = <ThrowOnError extends boolean = false>(options: Options<PostV1BotsByBotIdChannelsSlackConnectData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostV1BotsByBotIdChannelsSlackConnectResponse, PostV1BotsByBotIdChannelsSlackConnectError, ThrowOnError>({
        url: '/v1/bots/{botId}/channels/slack/connect',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getV1BotsByBotIdChannels = <ThrowOnError extends boolean = false>(options: Options<GetV1BotsByBotIdChannelsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetV1BotsByBotIdChannelsResponse, GetV1BotsByBotIdChannelsError, ThrowOnError>({
        url: '/v1/bots/{botId}/channels',
        ...options
    });
};

export const deleteV1BotsByBotIdChannelsByChannelId = <ThrowOnError extends boolean = false>(options: Options<DeleteV1BotsByBotIdChannelsByChannelIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteV1BotsByBotIdChannelsByChannelIdResponse, DeleteV1BotsByBotIdChannelsByChannelIdError, ThrowOnError>({
        url: '/v1/bots/{botId}/channels/{channelId}',
        ...options
    });
};

export const getV1BotsByBotIdChannelsByChannelIdStatus = <ThrowOnError extends boolean = false>(options: Options<GetV1BotsByBotIdChannelsByChannelIdStatusData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetV1BotsByBotIdChannelsByChannelIdStatusResponse, GetV1BotsByBotIdChannelsByChannelIdStatusError, ThrowOnError>({
        url: '/v1/bots/{botId}/channels/{channelId}/status',
        ...options
    });
};

export const postV1InviteValidate = <ThrowOnError extends boolean = false>(options?: Options<PostV1InviteValidateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostV1InviteValidateResponse, unknown, ThrowOnError>({
        url: '/v1/invite/validate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getV1Models = <ThrowOnError extends boolean = false>(options?: Options<GetV1ModelsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetV1ModelsResponse, unknown, ThrowOnError>({
        url: '/v1/models',
        ...options
    });
};

export const getApiInternalPoolsByPoolIdConfig = <ThrowOnError extends boolean = false>(options: Options<GetApiInternalPoolsByPoolIdConfigData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiInternalPoolsByPoolIdConfigResponse, GetApiInternalPoolsByPoolIdConfigError, ThrowOnError>({
        url: '/api/internal/pools/{poolId}/config',
        ...options
    });
};

export const postApiInternalPoolsRegister = <ThrowOnError extends boolean = false>(options?: Options<PostApiInternalPoolsRegisterData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiInternalPoolsRegisterResponse, unknown, ThrowOnError>({
        url: '/api/internal/pools/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const postApiInternalPoolsHeartbeat = <ThrowOnError extends boolean = false>(options?: Options<PostApiInternalPoolsHeartbeatData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiInternalPoolsHeartbeatResponse, unknown, ThrowOnError>({
        url: '/api/internal/pools/heartbeat',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getApiInternalPoolsByPoolIdConfigLatest = <ThrowOnError extends boolean = false>(options: Options<GetApiInternalPoolsByPoolIdConfigLatestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiInternalPoolsByPoolIdConfigLatestResponse, GetApiInternalPoolsByPoolIdConfigLatestError, ThrowOnError>({
        url: '/api/internal/pools/{poolId}/config/latest',
        ...options
    });
};

export const getApiInternalPoolsByPoolIdConfigVersionsByVersion = <ThrowOnError extends boolean = false>(options: Options<GetApiInternalPoolsByPoolIdConfigVersionsByVersionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponse, GetApiInternalPoolsByPoolIdConfigVersionsByVersionError, ThrowOnError>({
        url: '/api/internal/pools/{poolId}/config/versions/{version}',
        ...options
    });
};