// This file is auto-generated by @hey-api/openapi-ts

export type GetV1BotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/bots';
};

export type GetV1BotsResponses = {
    /**
     * Bot list
     */
    200: {
        bots: Array<{
            id: string;
            name: string;
            slug: string;
            poolId: string;
            status: 'active' | 'paused' | 'deleted';
            modelId: string;
            systemPrompt: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetV1BotsResponse = GetV1BotsResponses[keyof GetV1BotsResponses];

export type PostV1BotsData = {
    body?: {
        name: string;
        slug: string;
        systemPrompt?: string;
        modelId?: string;
        poolId?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/bots';
};

export type PostV1BotsErrors = {
    /**
     * Invalid pool state
     */
    400: {
        message: string;
    };
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
    /**
     * Slug already exists
     */
    409: {
        message: string;
    };
};

export type PostV1BotsError = PostV1BotsErrors[keyof PostV1BotsErrors];

export type PostV1BotsResponses = {
    /**
     * Bot created
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1BotsResponse = PostV1BotsResponses[keyof PostV1BotsResponses];

export type DeleteV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}';
};

export type DeleteV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type DeleteV1BotsByBotIdError = DeleteV1BotsByBotIdErrors[keyof DeleteV1BotsByBotIdErrors];

export type DeleteV1BotsByBotIdResponses = {
    /**
     * Bot deleted
     */
    200: {
        success: boolean;
    };
};

export type DeleteV1BotsByBotIdResponse = DeleteV1BotsByBotIdResponses[keyof DeleteV1BotsByBotIdResponses];

export type GetV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}';
};

export type GetV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type GetV1BotsByBotIdError = GetV1BotsByBotIdErrors[keyof GetV1BotsByBotIdErrors];

export type GetV1BotsByBotIdResponses = {
    /**
     * Bot details
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetV1BotsByBotIdResponse = GetV1BotsByBotIdResponses[keyof GetV1BotsByBotIdResponses];

export type PatchV1BotsByBotIdData = {
    body?: {
        name?: string;
        systemPrompt?: string;
        modelId?: string;
    };
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}';
};

export type PatchV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PatchV1BotsByBotIdError = PatchV1BotsByBotIdErrors[keyof PatchV1BotsByBotIdErrors];

export type PatchV1BotsByBotIdResponses = {
    /**
     * Bot updated
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchV1BotsByBotIdResponse = PatchV1BotsByBotIdResponses[keyof PatchV1BotsByBotIdResponses];

export type PostV1BotsByBotIdPauseData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/pause';
};

export type PostV1BotsByBotIdPauseErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostV1BotsByBotIdPauseError = PostV1BotsByBotIdPauseErrors[keyof PostV1BotsByBotIdPauseErrors];

export type PostV1BotsByBotIdPauseResponses = {
    /**
     * Bot paused
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1BotsByBotIdPauseResponse = PostV1BotsByBotIdPauseResponses[keyof PostV1BotsByBotIdPauseResponses];

export type PostV1BotsByBotIdResumeData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/resume';
};

export type PostV1BotsByBotIdResumeErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostV1BotsByBotIdResumeError = PostV1BotsByBotIdResumeErrors[keyof PostV1BotsByBotIdResumeErrors];

export type PostV1BotsByBotIdResumeResponses = {
    /**
     * Bot resumed
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1BotsByBotIdResumeResponse = PostV1BotsByBotIdResumeResponses[keyof PostV1BotsByBotIdResumeResponses];

export type GetV1BotsByBotIdChannelsSlackOauthUrlData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/channels/slack/oauth-url';
};

export type GetV1BotsByBotIdChannelsSlackOauthUrlErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
    /**
     * Slack OAuth not configured
     */
    500: {
        message: string;
    };
};

export type GetV1BotsByBotIdChannelsSlackOauthUrlError = GetV1BotsByBotIdChannelsSlackOauthUrlErrors[keyof GetV1BotsByBotIdChannelsSlackOauthUrlErrors];

export type GetV1BotsByBotIdChannelsSlackOauthUrlResponses = {
    /**
     * Slack OAuth authorization URL
     */
    200: {
        url: string;
    };
};

export type GetV1BotsByBotIdChannelsSlackOauthUrlResponse = GetV1BotsByBotIdChannelsSlackOauthUrlResponses[keyof GetV1BotsByBotIdChannelsSlackOauthUrlResponses];

export type PostV1BotsByBotIdChannelsSlackConnectData = {
    body?: {
        botToken: string;
        signingSecret: string;
        teamId: string;
        teamName?: string;
    };
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/channels/slack/connect';
};

export type PostV1BotsByBotIdChannelsSlackConnectErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
    /**
     * Slack already connected
     */
    409: {
        message: string;
    };
};

export type PostV1BotsByBotIdChannelsSlackConnectError = PostV1BotsByBotIdChannelsSlackConnectErrors[keyof PostV1BotsByBotIdChannelsSlackConnectErrors];

export type PostV1BotsByBotIdChannelsSlackConnectResponses = {
    /**
     * Slack channel connected
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1BotsByBotIdChannelsSlackConnectResponse = PostV1BotsByBotIdChannelsSlackConnectResponses[keyof PostV1BotsByBotIdChannelsSlackConnectResponses];

export type GetV1BotsByBotIdChannelsData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/channels';
};

export type GetV1BotsByBotIdChannelsErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type GetV1BotsByBotIdChannelsError = GetV1BotsByBotIdChannelsErrors[keyof GetV1BotsByBotIdChannelsErrors];

export type GetV1BotsByBotIdChannelsResponses = {
    /**
     * Channel list
     */
    200: {
        channels: Array<{
            id: string;
            botId: string;
            channelType: 'slack';
            accountId: string;
            status: 'pending' | 'connected' | 'disconnected' | 'error';
            teamName: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetV1BotsByBotIdChannelsResponse = GetV1BotsByBotIdChannelsResponses[keyof GetV1BotsByBotIdChannelsResponses];

export type DeleteV1BotsByBotIdChannelsByChannelIdData = {
    body?: never;
    path: {
        botId: string;
        channelId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/channels/{channelId}';
};

export type DeleteV1BotsByBotIdChannelsByChannelIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteV1BotsByBotIdChannelsByChannelIdError = DeleteV1BotsByBotIdChannelsByChannelIdErrors[keyof DeleteV1BotsByBotIdChannelsByChannelIdErrors];

export type DeleteV1BotsByBotIdChannelsByChannelIdResponses = {
    /**
     * Channel disconnected
     */
    200: {
        success: boolean;
    };
};

export type DeleteV1BotsByBotIdChannelsByChannelIdResponse = DeleteV1BotsByBotIdChannelsByChannelIdResponses[keyof DeleteV1BotsByBotIdChannelsByChannelIdResponses];

export type GetV1BotsByBotIdChannelsByChannelIdStatusData = {
    body?: never;
    path: {
        botId: string;
        channelId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/channels/{channelId}/status';
};

export type GetV1BotsByBotIdChannelsByChannelIdStatusErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetV1BotsByBotIdChannelsByChannelIdStatusError = GetV1BotsByBotIdChannelsByChannelIdStatusErrors[keyof GetV1BotsByBotIdChannelsByChannelIdStatusErrors];

export type GetV1BotsByBotIdChannelsByChannelIdStatusResponses = {
    /**
     * Channel status
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetV1BotsByBotIdChannelsByChannelIdStatusResponse = GetV1BotsByBotIdChannelsByChannelIdStatusResponses[keyof GetV1BotsByBotIdChannelsByChannelIdStatusResponses];

export type PostV1InviteValidateData = {
    body?: {
        code: string;
    };
    path?: never;
    query?: never;
    url: '/v1/invite/validate';
};

export type PostV1InviteValidateResponses = {
    /**
     * Validation result
     */
    200: {
        valid: boolean;
        message?: string;
    };
};

export type PostV1InviteValidateResponse = PostV1InviteValidateResponses[keyof PostV1InviteValidateResponses];

export type GetV1ModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type GetV1ModelsResponses = {
    /**
     * Available models
     */
    200: {
        models: Array<{
            id: string;
            name: string;
            provider: string;
            isDefault?: boolean;
            description?: string;
        }>;
    };
};

export type GetV1ModelsResponse = GetV1ModelsResponses[keyof GetV1ModelsResponses];

export type GetApiInternalPoolsByPoolIdConfigData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config';
};

export type GetApiInternalPoolsByPoolIdConfigErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigError = GetApiInternalPoolsByPoolIdConfigErrors[keyof GetApiInternalPoolsByPoolIdConfigErrors];

export type GetApiInternalPoolsByPoolIdConfigResponses = {
    /**
     * Generated OpenClaw config
     */
    200: {
        gateway: {
            port?: number;
            mode?: 'local';
            bind?: 'loopback' | 'lan' | 'auto';
            auth: {
                mode: 'none' | 'token';
                token?: string;
            };
            reload?: {
                mode: 'off' | 'hot' | 'hybrid';
            };
        };
        models?: {
            mode?: 'merge' | 'replace';
            providers: {
                [key: string]: {
                    baseUrl: string;
                    apiKey: string;
                    api: string;
                    models: Array<{
                        id: string;
                        name?: string;
                        reasoning?: boolean;
                        input?: Array<string>;
                        cost?: {
                            input: number;
                            output: number;
                            cacheRead?: number;
                            cacheWrite?: number;
                        };
                        contextWindow?: number;
                        maxTokens?: number;
                        compat?: {
                            supportsStore?: boolean;
                        };
                    }>;
                };
            };
        };
        agents: {
            defaults?: {
                model?: string | {
                    primary: string;
                };
            };
            list: Array<{
                id: string;
                name?: string;
                default?: boolean;
                workspace?: string;
                model?: string | {
                    primary: string;
                    fallbacks?: Array<string>;
                };
            }>;
        };
        channels: {
            slack?: {
                mode?: 'socket' | 'http';
                signingSecret?: string;
                enabled?: boolean;
                groupPolicy?: 'open' | 'allowlist' | 'disabled';
                requireMention?: boolean;
                dmPolicy?: 'pairing' | 'allowlist' | 'open';
                allowFrom?: Array<string>;
                accounts: {
                    [key: string]: {
                        enabled?: boolean;
                        botToken: string;
                        signingSecret?: string;
                        appToken?: string;
                        mode?: 'socket' | 'http';
                        webhookPath?: string;
                        dmPolicy?: 'pairing' | 'allowlist' | 'open';
                        groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    };
                };
            };
        };
        bindings: Array<{
            agentId: string;
            match: {
                channel: string;
                accountId?: string;
            };
        }>;
        commands?: {
            native?: 'auto' | 'off';
            nativeSkills?: 'auto' | 'off';
            restart?: boolean;
            ownerDisplay?: 'raw' | 'friendly';
        };
    };
};

export type GetApiInternalPoolsByPoolIdConfigResponse = GetApiInternalPoolsByPoolIdConfigResponses[keyof GetApiInternalPoolsByPoolIdConfigResponses];

export type PostApiInternalPoolsRegisterData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/register';
};

export type PostApiInternalPoolsRegisterResponses = {
    /**
     * Pool node registered
     */
    200: {
        ok: boolean;
        poolId: string;
    };
};

export type PostApiInternalPoolsRegisterResponse = PostApiInternalPoolsRegisterResponses[keyof PostApiInternalPoolsRegisterResponses];

export type PostApiInternalPoolsHeartbeatData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
        lastSeenVersion?: number;
        timestamp?: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/heartbeat';
};

export type PostApiInternalPoolsHeartbeatResponses = {
    /**
     * Pool node heartbeat accepted
     */
    200: {
        ok: boolean;
        poolId: string;
        status: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
};

export type PostApiInternalPoolsHeartbeatResponse = PostApiInternalPoolsHeartbeatResponses[keyof PostApiInternalPoolsHeartbeatResponses];

export type GetApiInternalPoolsByPoolIdConfigLatestData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/latest';
};

export type GetApiInternalPoolsByPoolIdConfigLatestErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestError = GetApiInternalPoolsByPoolIdConfigLatestErrors[keyof GetApiInternalPoolsByPoolIdConfigLatestErrors];

export type GetApiInternalPoolsByPoolIdConfigLatestResponses = {
    /**
     * Latest pool config snapshot
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestResponse = GetApiInternalPoolsByPoolIdConfigLatestResponses[keyof GetApiInternalPoolsByPoolIdConfigLatestResponses];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionData = {
    body?: never;
    path: {
        poolId: string;
        version?: number;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/versions/{version}';
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors = {
    /**
     * Config version not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionError = GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses = {
    /**
     * Pool config snapshot by version
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponse = GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};